### ISSUE TITLE
Jobs to be done study

### ISSUE THREAD

**Issue by tashimi** [kubernetes-sigs/sig-usability#9]
User Interviews

Background
This proposal is part of our Kubernetes Jobs-to-be-Done long term effort. We sent out a survey via the CNCF Twitter which ran from April 3 to ~May 29th 2020, overall 8 weeks. We collected 118 responses and 41 (34%) of those agreed to be contacted for details on their answers. This means we can move on to the next part of our plan: user interviews!

Goal
Conduct 10-15 jobs-to-be-done interviews that will allow us to deep dive into the goals that users have in using Kubernetes, including key use cases, and the steps they take to achieve these. 

Outcome
A concrete list of use cases broken down by steps to achieve them.

2020 in review
Define interview script
Define data collection protocol
Scheduled 2 interviews
Conducted 2 interviews

2021 plan
Conduct 2 interviews per month, 10-15 interviews total
Begin analysis mid year

**Comment by tashimi** [comment]
More info here: https://docs.google.com/document/d/1sDkGXftIEHKD_sMfgyWtP2QAFV7E0iB7XdCbO0ebvY0/edit#

**Comment by rachejazz** [comment]
Hello @tashimi , just came across the mentorship program at TLF website. What is the type of service one will learn during the program as a mentee?

Provided she has a basic idea of k8s and is fairly well at containerization(Docker inc.)
Thank you.

**Comment by arnav-t** [comment]
Hi, what skills are required or expected to be put to use during the course of this mentorship?

**Comment by tashimi** [comment]
Hi @rachejazz & @arnav-t : this is really a UX focused mentorship, so it would be of most interest to someone who's interested in user experience, user research, etc.

You will be shadowing some UX researcher leads as they interview Kubernetes users, and helping to compile data that we will be using to put together a Jobs to be done study. This study will be presented at Kubecon and the data in it will be used to help drive understanding of how are users are using Kubernetes, and what we should invest in to improve their experience.

**Comment by rachejazz** [comment]
Any updates to the future of this mentorship? Saw nothing on mentor site of lfx

**Comment by alphaX86** [comment]
@tashimi I applied for the program as a mentee but I still didn't get any message regarding it... Could you look at my profile at LFX and check? Thanks!

**Comment by sreenathpranav** [comment]
Hi I am really interested in this program and I want to part of this program is the deadline for application over?
